cors:
    originPatterns: http://localhost:8080,http://localhost:3000
spring:
    application:
        name: bookstore-virtual-assistant-ai
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            chat:
                options:
                    model: gpt-4o-mini
                    temperature: 0.7