apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-virtual-assistant-ai-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bookstore-virtual-assistant-ai-api
  template:
    metadata:
      labels:
        app: bookstore-virtual-assistant-ai-api
    spec:
      containers:
        - name: bookstore-virtual-assistant-ai-api
          image: pedroaugustoengineer/bookstore-virtual-assistant-ai-api:v${{ github.run_number }}
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: 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
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-virtual-assistant-ai-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookstore-virtual-assitant-ai-api

