apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-virtual-assistant-ai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-virtual-assistant-ai-api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true" # habilities the prometheus
        prometheus.io/path: /metrics # definies the path to the collected metrics
        prometheus.io/port: "80"  # definies the port of the prometheus server 
      labels:
        app: bookstore-virtual-assistant-ai-api
    spec:
      containers:
        - name: bookstore-virtual-assistant-ai-api
          image: pedroaugustoengineer/bookstore-virtual-assistant-ai-api:v${{ github.run_number }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: bookstore-virtual-assistant-ai-api-config
              
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-virtual-assistant-ai-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bookstore-virtual-assistant-ai-api


