on:
  push:
    branches:
      - "main"
      - "feature/**"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve and Copy the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup JDK amazoncorretto-23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          cache: maven
          
      - name: Build .jar with Maven
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn -Dtest=unittest/** test

      #- name: Run Integration Tests
        #working-directory: ./
        #run: mvn -Dtest=integrationtests/** test
      
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=bookstore-virtual-assistant
          projectBaseDir: ./
          scanMetadataReportFile: ./.scannerwork/report-task.txt
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar


