name: CI
on:
  push:
    branches:
      - "main"
      - "feature/**"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve and Copy the repository code
        uses: actions/checkout@v4
      
      - name: Setup JDK amazoncorretto-23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          cache: maven
          
      - name: Build .jar with Maven
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn -Dtest=unittest/** test

      #- name: Run Integration Tests
        #working-directory: ./
        #run: mvn -Dtest=integrationtests/** test
      
  
